name: Build and Deploy

on:
    push:
      branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: Use Node.js 14
              uses: actions/setup-node@v2
              with:
                node-version: '14'
                
            - name: Installing dependencies
              run: npm install
              
            - name: Building the Application
              run: npm run build
              env: 
                AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
                AUTH0_CLIENTID: ${{ secrets.AUTH0_CLIENTID }}
            
            - name: Upload to S3
              uses: jakejarvis/s3-sync-action@v0.5.0
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
                AWS_REGION: 'eu-west-1'
                SOURCE_DIR: 'dist/rfkode-ng'